// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AppController from "./app_controller"
application.register("app", AppController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import MortgageCalculatorController from "./mortgage_calculator_controller"
application.register("mortgage-calculator", MortgageCalculatorController)
