# frozen_string_literal: true

# Phase 2C.1 — cached LLM-generated SEO meta for each Property.
#
# Generated by Seo::PropertyMetaGenerator via OmniClient analysis chain
# (free-first: openai/gpt-oss-120b free → Gemini Flash → Sonnet fallback).
# Stored on the Property itself so:
#   • property show view reads in O(1) without LLM round-trip
#   • sitemap.xml + JSON-LD pull pre-canonicalised titles
#   • re-generation is opt-in (rake seo_generation:property_meta:regenerate[id])
#
# Length budgets reflect SEO best practice (Google + Yandex):
#   seo_title       ≤ 70  chars  (Google clips ~60, Yandex ~70)
#   seo_description ≤ 200 chars  (snippet)
#   seo_h1          ≤ 90  chars  (visible heading)
#
# `seo_generated_at` lets us prioritise stale entries during backfill.
# `seo_model` records which chain model produced the output — useful for
# debugging quality regressions when a free tier rotates models.
class AddSeoFieldsToProperties < ActiveRecord::Migration[7.1]
  def change
    change_table :properties, bulk: true do |t|
      t.string   :seo_title,         limit: 90
      t.text     :seo_description
      t.string   :seo_h1,            limit: 120
      t.datetime :seo_generated_at
      t.string   :seo_model,         limit: 100
    end

    # Partial index for the backfill task (`WHERE seo_generated_at IS NULL`).
    add_index :properties, :seo_generated_at,
              where: 'seo_generated_at IS NULL',
              name: 'idx_properties_seo_pending'
  end
end
